---
language: go

sudo: false

addons:
  apt:
    packages:
      # hammer
      - rpm

cache:
  bundler: true
  directories:
    - .build-info

install:
  # packages for packaging
  - go get -v github.com/asteris-llc/hammer
  - gem install fpm

script:
  - ./scripts/travis.sh

after_failure:
  - tail logs/*

deploy:
  provider: script
  script: /bin/bash scripts/bintray.sh /tmp/out
  on:
    branch: master
