---
language: go

sudo: false

addons:
  apt:
    packages:
      # hammer
      - rpm

cache:
  bundler: true
  directories:
    - .build-info

install:
  # packages for packaging
  - go get -v github.com/asteris-llc/hammer
  - gem install fpm

  # set cache if not set
  - "[[ ! -f .build-info/last-build ]] && git rev-list --max-parents=0 HEAD > .build-info/last-build"

script:
  - hammer build --output=/tmp/out $PACKAGE

after_failure:
  - tail logs/*

deploy:
  provider: script
  script: /bin/bash scripts/bintray.sh /tmp/out
  on:
    branch: master
