---
name: traefik
version: 0.0.0
epoch: 285
iteration: 7
license: MIT
vendor: Emile Vauge
architecture: x86_64
type: rpm
url: https://github.com/EmileVauge/traefik
description: Træfɪk, a modern reverse proxy

dependencies:
  - libcap
  - python
  - sudo

resources:
  - url: https://github.com/emilevauge/traefik/releases/download/v1.0.alpha.285/traefik_linux-amd64
    hash-type: sha1
    hash: 01564a14919fd364000e085e4aa2a29d134d3d90

targets:
  # base
  - src: '{{.BuildRoot}}/traefik_linux-amd64'
    dest: /usr/bin/{{.Name}}
  - src: '{{.SpecRoot}}/{{.Name}}.service'
    dest: /etc/systemd/system/{{.Name}}.service
    template: yes
  - src: '{{empty}}'
    dest: /etc/traefik
  - src: '{{empty}}'
    dest: /etc/traefik/configs
  - src: '{{.SpecRoot}}/logrotate/traefik'
    dest: /etc/logrotate.d/
  - src: '{{.SpecRoot}}/logrotate/traefik-access'
    dest: /etc/logrotate.d/

  # config generation scripts
  - src: '{{.SpecRoot}}/config/'
    dest: /usr/bin/
  - src: '{{.SpecRoot}}/traefik-restart'
    dest: /etc/sudoers.d/

scripts:
  before-install: |
    getent group {{.Name}} > /dev/null || groupadd -r {{.Name}}
    getent passwd {{.Name}} > /dev/null || \
        useradd -r \
                -g {{.Name}} \
                -d /etc/{{.Name}} \
                -s /sbin/nologin \
                -c "{{.Name}} user" \
                {{.Name}}

  after-install: |
    chown -R {{.Name}}:{{.Name}} /etc/{{.Name}}
    chown -R {{.Name}}:{{.Name}} /var/log/{{.Name}}

    setcap 'cap_net_bind_service=+ep' /usr/bin/{{.Name}}

    systemctl enable /etc/systemd/system/{{.Name}}.service 2>/dev/null
    systemctl start {{.Name}}.service

    sudo -u {{.Name}} traefik-global --port=80 \
                                      --grace-time-out=10 \
                                      --access-logs-file=/var/log/{{.Name}}/access.log
                                      --traefik-logs-file=/var/log/{{.Name}}/traefik.log
    sudo -u {{.Name}} traefik-web --address=:8080

  after-upgrade: |
    setcap 'cap_net_bind_service=+ep' /usr/bin/{{.Name}}

    systemctl daemon-reload
    systemctl restart {{.Name}}.service

  before-remove: |
    systemctl stop {{.Name}}.service
    systemctl disable {{.Name}}.service 2>/dev/null

  after-remove: |
    systemctl daemon-reload

extra-args: |
  --rpm-os linux
  --rpm-auto-add-directories
  --rpm-auto-add-exclude-directories /etc/systemd
  --rpm-auto-add-exclude-directories /etc/systemd/system
  --rpm-auto-add-exclude-directories /etc/sudoers.d
